version: "3.8"

services:
  web:
    image: php:8.2-apache
    container_name: vtiger_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - vtiger_network

  db:
    image: mysql:8.0
    container_name: vtiger_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 132120
      MYSQL_DATABASE: TDB1
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - vtiger_network
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: vtiger_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: 132120
    depends_on:
      - db
    networks:
      - vtiger_network

networks:
  vtiger_network:
    driver: bridge

volumes:
  mysql_data:
    name: tdb-vtiger_mysql_data
    external: true

